AllCops:
  Exclude: 
    - spec/**/*
    - db/migrate/*
    - db/schema.rb
    - config.ru
    - application.rb
    - Gemfile
    - Rakefile
  RubyInterpreters:
    - ruby
Layout/LineLength:
  Max: 125
Documentation:
  Enabled: false
